bib: improve error when a container does not contain a default rootfs
Tweak the error output when a bootc container does not contain a
default filesystem. The new error will hint what commandline option
to use. The error message generation is also moved from the helper
into the main program because only the main.go knows what options
it supports.

The error is now:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
Error: cannot generate manifest: no default root filesystem type specified in container, please use "--rootfs" to set manually
2024/06/24 11:39:39 error: cannot generate manifest: no default root filesystem type specified in container, please use "--rootfs" to set manually
```